version: '{build}'
environment:
  matrix:
  - PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
  - PYTHON: "C:\\Python34"
    PYTHON_VERSION: "3.4.1"
    PYTHON_ARCH: "32"
  - PYTHON: "C:\\Python34-x64"
    PYTHON_VERSION: "3.4.1"
    PYTHON_ARCH: "64"
install:
- SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
- python --version
- python -m pip install --upgrade setuptools pip wheel
- appveyor\\run.cmd python -m pip install --cache-dir=C:\wheelhouse -r requirements.txt
cache: C:\wheelhouse
build: off
test_script:
- python -m pytest touchdown
notifications:
  - provider: Slack
    auth_token:
      secure: 3B+1y9v9ei1yPhW9DEy75z+OdRATgFN3ktUTIAqpcvm6ObcJ+aZcuohLqs0Mk5Qf4Kl+1FbsZ1F3kDxr+4pkoA==
    channel: general
